server:
  port: 8282

api:
  version: v1.0

spring:
  application:
    name: photocatalog
  graphql:
    graphiql:
      enabled: true
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'photocatalog-consumer'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:postgresql://localhost:5432/photocatalog'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      schema: photocatalog
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: photocatalog
    locations: classpath:db/migration/photocatalog
